config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "home", to: "home#index"

  resources :books, only: [ :index, :show, :new, :create,:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author,presence: true
  validates :page_count, numericality: { only_integer: true, greater_than: 0}, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update]

  def show
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
  @book = Book.new(book_params)

  if @book.save
    redirect_to books_path
  else
    render :new
  end

end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to books_path
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :page_count, :published_at)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<h1> Creer un nouveau livre </h1>

<%= form_with model: @book, local: true do |form| %>

  <% if @book.errors.any? %>
  <h2>
    an error prohibited this book from beeing saved:
  </h2>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :page_count %><br>
    <%= form.number_field :page_count %>
  </p>

  <p>
    <%= form.label :published_at %><br>
    <%= form.text_field :published_at %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<h1> Tout les livres </h1><br>
<td><%= link_to "nouveau livre", new_book_url %></td><br>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= link_to "Voir", book_path(book) %></td>
      <td><%= link_to "Modifier", edit_book_path(book) %></td>

    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><strong><%= @book.author %> - <%= @book.published_at %> - <%= @book.page_count %></strong></p>
<p><%= @book.description %></p>

app/views/home/index.html.erb
<h1>Base de données</h1>
<p>pas encore disponible revenez plus tard</p>
<h1><%=link_to "Tout nos livres", books_path %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>